/*
 * Member register: the MDA of each affiliated staff multi-purpose cooperative society.
 * Society name = `${mda} Staff Multi-purpose Cooperative Society` (NAME_OVERRIDES for exceptions).
 * Imported with `npx convex run seed:importRegister`.
 */

export const REGISTER_MDAS = [
  "Agricultural Research Council of Nigeria",
  "Asset Management Corporation of Nigeria",
  "Border Communities Development Agency",
  "Broadcasting Organisation of Nigeria",
  "Budget Office of the Federation",
  "Bureau of Public Enterprises",
  "Central Bank of Nigeria",
  "Centre for Black and African Arts and Civilization",
  "Cocoa Research Institute of Nigeria",
  "Code of Conduct Bureau",
  "Consumer Protection Council",
  "Corporate Affairs Commission",
  "Debt Management Office",
  "Defence Intelligence Agency",
  "Economic and Financial Crimes Commission",
  "Electricity Management Services Limited",
  "Energy Commission of Nigeria",
  "Federal Airports Authority of Nigeria",
  "Federal Character Commission",
  "Federal Fire Service",
  "Federal Housing Authority",
  "Federal Inland Revenue Service",
  "Federal Judicial Service Commission",
  "Federal Mortgage Bank of Nigeria",
  "Federal Road Safety Corps",
  "Fiscal Responsibility Commission",
  "Forestry Research Institute of Nigeria",
  "Galaxy Backbone",
  "Independent Corrupt Practices and Other Related Offences Commission",
  "Independent National Electoral Commission",
  "Industrial Training Fund",
  "Legal Aid Council of Nigeria",
  "National Agency for Food and Drug Administration and Control",
  "National Agency For Science and Engineering Infrastructure",
  "National Agency for the Control of AIDS",
  "National Agency for the Prohibition of Trafficking in Persons",
  "National Agricultural Extension, Research and Liaison Services",
  "National Automotive Design and Development Council",
  "National Biosafety Management Agency",
  "National Biotechnology Development Agency",
  "National Boundary Commission",
  "National Bureau of Statistics",
  "National Business and Technical Examinations Board",
  "National Centre for Remote Sensing",
  "National Centre for Technology Management",
  "National Commission for Colleges of Education",
  "National Council of Arts and Culture",
  "National Council on Privatisation",
  "National Drug Law Enforcement Agency",
  "National Emergency Management Agency",
  "National Energy Council",
  "National Environmental Standards and Regulations Enforcement Agency",
  "National Film and Video Censors Board",
  "National Frequency Management Council",
  "National Health Insurance Authority",
  "National Horticultural Research Institute",
  "National Human Rights Commission",
  "National Identity Management Commission",
  "National Information Technology Development Agency",
  "National Inland Waterways Authority",
  "National Institute for Hospitality Tourism",
  "National Institute for Pharmaceutical Research and Development",
  "National Insurance Commission",
  "National Intelligence Agency",
  "National Judicial Council",
  "National Judicial Institute",
  "National Library of Nigeria",
  "National Lottery Trust Fund",
  "National Open University of Nigeria",
  "National Orientation Agency",
  "National Pension Commission",
  "National Planning Commission",
  "National Population Commission",
  "National Poverty Eradication Programme",
  "National Power Training Institute of Nigeria",
  "National Primary Health Care Development Agency",
  "National Root Crops Research Institute",
  "National Salaries, Incomes and Wages Commission",
  "National Space Research and Development Agency",
  "National Sports Commission",
  "National Sugar Development Council",
  "National Teachers Institute",
  "National Television Authority",
  "National Universities Commission",
  "National Veterinary Research Institute",
  "National Water Resources Institute",
  "New Partnership for African Development",
  "News Agency of Nigeria",
  "Niger Delta Development Commission",
  "Nigeria Agricultural Quarantine Service",
  "Nigeria Atomic Energy Commission",
  "Nigeria Centre for Disease Control",
  "Nigeria Communications Satellite Limited",
  "Nigeria Customs Service",
  "Nigeria Deposit Insurance Corporation",
  "Nigeria Export Processing Zones Authority",
  "Nigeria Extractive Industries Transprency Initiative",
  "Nigeria Hydrological Services Agency",
  "Nigeria Immigration Service",
  "Nigeria Investment Promotion Commission",
  "Nigeria National Merit Award",
  "Nigeria Security and Civil Defence Corps",
  "Nigerian Agricultural Insurance Corporation",
  "Nigerian Airspace Management Agency",
  "Nigerian Broadcasting Commission",
  "Nigerian Building and Road Research Institute",
  "Nigerian Civil Aviation Authority",
  "Nigerian College of Aviation Technology",
  "Nigerian Communications Commission",
  "Nigerian Communications Satellite Ltd",
  "Nigerian Copyright Commission",
  "Nigerian Correctional Service",
  "Nigerian Education Loan Fund",
  "Nigerian Electricity Regulatory Commission",
  "Nigerian Export - Import Bank",
  "Nigerian Export Promotion Council",
  "Nigerian Extractive Industries Transparency Initiative",
  "Nigerian Financial Intelligence Unit",
  "Nigerian Institute for Oceanography and Marine Research",
  "Nigerian Institute for Oil Palm Research",
  "Nigerian Institute of Medical Research",
  "Nigerian Integrated Water Resources Commission",
  "Nigerian Law School",
  "Nigerian Maritime Administration and Safety Agency",
  "Nigerian Meteorological Agency",
  "Nigerian Midstream and Downstream Petroleum Regulatory Authority",
  "Nigerian National Petroleum Corporation",
  "Nigerian Nuclear Regulatory Authority",
  "Nigerian Ports Authority",
  "Nigerian Postal Service",
  "Nigerian Press Council",
  "Nigerian Safety Investigation Bureau",
  "Nigerian Shippers' Council",
  "Nigerian Television Authority",
  "Nigerian Tourism Development Corporation",
  "Nigerian Upstream Petroleum Regulatory Commission",
  "Oil and Gas Free Zones Authority",
  "Petroleum Product Pricing Regulatory Agency",
  "Power Holding Company of Nigeria",
  "Public Complaints Commission, Nigeria",
  "Raw Materials Research and Development Council",
  "Revenue Mobilisation Allocation and Fiscal Commission",
  "Revenue, Mobilization, Allocation & Fiscal Commission",
  "River Basin Development Authorities",
  "Rural Electrification Agency",
  "Securities and Exchange Commission",
  "SERVICOM",
  "Sheda Science and Technology Complex",
  "Small and Medium Enterprise Development Agency of Nigeria",
  "Social Security Administration of Nigeria",
  "Standards Organisation of Nigeria",
  "State Security Service",
  "Surveyors Council Of Nigeria",
  "Tertiary Education Trust Fund",
  "Transmission Company of Nigeria",
  "Universal Basic Education Commission",
  "West African Examination Council",
] as const;

export const NAME_OVERRIDES: Record<string, string> = {
  "National Film and Video Censors Board": "National Film and Video Censors Board Staff Multi-purpose Co-operative Society",
  "Nigerian Law School": "Nigerian Law School Staff Multipurpose Cooperative Society",
};

export const societyName = (mda: string) => NAME_OVERRIDES[mda] ?? `${mda} Staff Multi-purpose Cooperative Society`;

export const slugify = (s: string) =>
  s
    .toLowerCase()
    .replace(/&/g, " and ")
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
